In [6]:
import pandas as pd 
import numpy as np 
import os

In [7]:
data = pd.read_csv('../data/AAPL20250102_original.csv', index_col = 1)
data = data.drop(columns = ['ts_recv','rtype', 'publisher_id', 'instrument_id', 'flags', 'ts_in_delta', 'sequence'])
data = data.drop(columns=[col for col in data.columns if any(char.isdigit() for char in col) and (int(''.join(filter(str.isdigit, col))) > 5 or int(''.join(filter(str.isdigit, col))) == 0)])
data.dropna(inplace=True)

data.head(10)

,action,side,depth,price,size,bid_px_01,ask_px_01,bid_sz_01,ask_sz_01,bid_ct_01,...,ask_sz_04,bid_ct_04,ask_ct_04,bid_px_05,ask_px_05,bid_sz_05,ask_sz_05,bid_ct_05,ask_ct_05,symbol
ts_event,,,,,,,,,,,,,,,,,,,,,
2025-01-02 09:00:01.193543605+00:00,A,A,2,254.00,20,248.18,251.90,399,120,1,...,4,1,1,202.75,296.36,10,3,1,1,AAPL
2025-01-02 09:00:01.223799811+00:00,A,A,4,267.73,5,248.18,251.90,399,120,1,...,5,1,1,202.75,271.27,10,4,1,1,AAPL
2025-01-02 09:00:01.225733734+00:00,A,B,3,238.44,5,248.18,251.90,399,120,1,...,5,1,1,236.33,271.27,40,4,1,1,AAPL
2025-01-02 09:00:01.391336672+00:00,A,B,1,251.16,29,251.16,251.90,29,120,1,...,5,1,1,237.05,271.27,1,4,1,1,AAPL
2025-01-02 09:00:01.458667661+00:00,A,A,1,251.53,27,251.16,251.53,29,27,1,...,399,1,1,237.05,267.73,1,5,1,1,AAPL
2025-01-02 09:00:01.674388803+00:00,C,B,0,251.17,200,248.18,251.53,399,27,1,...,399,1,1,236.33,267.73,40,5,1,1,AAPL
2025-01-02 09:00:01.674401932+00:00,A,B,1,251.14,200,251.14,251.53,200,27,1,...,399,1,1,237.05,267.73,1,5,1,1,AAPL
2025-01-02 09:00:01.993068686+00:00,A,B,2,251.11,28,251.14,251.53,200,27,1,...,399,1,1,238.44,267.73,5,5,1,1,AAPL
2025-01-02 09:00:02.288070034+00:00,C,B,0,251.16,29,251.11,251.53,28,27,1,...,399,1,1,237.05,267.73,1,5,1,1,AAPL
2025-01-02 09:00:03.438169085+00:00,C,A,0,251.48,200,251.11,251.90,28,120,1,...,5,1,1,237.05,271.27,1,4,1,1,AAPL

In [9]:
data.to_csv('../data/AAPL20250102_after.csv')